name: Automatic Data Preprocessing

on:
  push:
    branches:
      - main
    paths:
      - "heart_attack_raw/**"
      - "preprocessing/automate_tandry-simamora.py"

jobs:
  run-preprocessing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy

      - name: Run Preprocessing Script
        run: python preprocessing/automate_Nama-Anda.py

      - name: Upload Processed Dataset Artifact
        uses: actions/upload-artifact@v4
        with:
          name: processed-heart-attack-dataset # Nama artifact yang akan muncul
          path: preprocessing/namadataset_preprocessing/heart_attack_preprocessed.csv # Path ke file yang ingin diunggah
